version: '3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=keycloak
      - PGDATA=/var/lib/postgresql/db
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - ./data/postgres:/var/lib/postgresql/db
  keycloak:
    image: jboss/keycloak:10.0.0
    depends_on:
      - postgres
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=postgres
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    volumes:
      - ./extras/training-theme:/opt/jboss/keycloak/themes/training-theme
    ports:
      - 8000:8080



