version: '3'
services:
  echo-server:
    image: landrzejewski/echo-server:v1
    ports:
      - 8080:8080
  postgres:
    image: postgres:11.2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=training
      - PGDATA=/var/lib/postgresql/db
    volumes:
    - ./data:/var/lib/postgresql/db
  pgadmin:
    image: dpage/pgadmin4:4
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=db@training.pl
      - PGADMIN_DEFAULT_PASSWORD=admin